# Generated by Django 4.2.7 on 2024-01-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email_adress', models.CharField(max_length=60)),
                ('Phone', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('Date', models.CharField(max_length=60)),
                ('message', models.CharField(max_length=100)),
            ],
        ),
    ]
